# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: npm install, build and test
        working-directory: client
        run: |
          npm install
          npm run build --if-present
          npm test
  
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Push to Docker Hub client
        uses: docker/build-push-action@v3
        with:
          context : ./client
          push: true
          tags: avisangolkar/multi-client:latest, avisangolkar/multi-client:${{github.run_number}}
      
      - name : Build & Push to Docker Hub Nginx
        uses: docker/build-push-action@v3
        with:
          context : ./nginx
          push: true
          tags: avisangolkar/multi-nginx:latest, avisangolkar/multi-nginx:${{github.run_number}}
      
      - name : Build & Push to Docker Hub Server
        uses: docker/build-push-action@v3
        with:
          context : ./server
          push: true
          tags: avisangolkar/multi-server:latest, avisangolkar/multi-server:${{github.run_number}}

      - name : Build & Push to Docker Hub Worker
        uses: docker/build-push-action@v3
        with:
          context : ./worker
          push: true
          tags: avisangolkar/multi-worker:latest, avisangolkar/multi-worker:${{github.run_number}}
      
      - name: Generate Deployment Package
        run: zip -r deploy_package.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      
      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://asangolkar-multi-docker/


          

    
